name: Tableau Workbook Workflows

on:
  push:
    branches: [ main ]
    paths:
      - 'tableau_workbook/**'
      
  pull_request:
    branches: [ main ] 
    paths:
      - 'tableau_workbook/**'

  workflow_dispatch:

jobs:
  tableau-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Tableau Workbook Deployments Action'
        uses: jayamanikharyono/tableau-workbook-action@v1.4
        env:
          USERNAME: saad.rehman456@gmail.com
          PASSWORD: ABS@@d123
          SITE_ID: saadpractice
          TABLEAU_URL: https://prod-apsoutheast-a.online.tableau.com/#/site/saadpractice/personalSpace
        with:
          workbook_dir: tableau_workbook/workbooks
          env: production
          repo_token: ${{ secrets.GIT_TOKEN }}
